[advisories]
unmaintained = "all"
maximum-db-staleness = "P30D"

[licenses]
allow = [
    "Apache-2.0",
    "BSL-1.0",
    "MIT",
    "Unicode-3.0",
    "Unlicense",
]

[bans]
multiple-versions = "warn"
wildcards = "deny"
allow-wildcard-paths = true
highlight = "all"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []
